server:
  port: 9080
  servlet:
    context-path: /spring-pagination-sorting

spring:
  data:
    mongodb:
      uri: mongodb://admin:masterkey@localhost:27017/pagination?authSource=admin
      auto-index-creation: true

springdoc:
  packagesToScan: br.com.example.spring.pagination.sorting.sample.controller
  pathsToMatch: /**